x-playwright-base: &playwright-base
  build:
    context: .
  environment:
    HEADLESS: "true"
  volumes:
    - ./playwright-report:/app/playwright-report
    - ./reports:/app/reports
    - ./test-results:/app/test-results

services:
  playwright:
    <<: *playwright-base
    command: npm test

  playwright-parallel:
    <<: *playwright-base
    profiles: ["parallel"]
    command: npm run test:parallel
